blank_issues_enabled: false
contact_links:
  - name: xDrip Issues, Feature requests, and Questions
    url: https://github.com/NightscoutFoundation/xDrip/discussions
    description: "Your feedback is very valuable.  Thanks for taking the time to provide it.  
    Please use "Discussions" (link on the right) to go to Discussions.  Then, click on "New discussion" to start a new thread.  
    To report an issue, please include what version of xDrip you are using, what your phone brand and model is, the steps you took that led to the issue.  
    To submit a feature request, please explain what you need to accomplish that you cannot with xDrip as is."
