blank_issues_enabled: false
contact_links:
  - name: xDrip Issues, Feature requests, and Questions
    url: https://github.com/NightscoutFoundation/xDrip/discussions
    about: |
      Please let us manage the issues.  Your input is very valuable.  Thanks for taking the time to provide it.  Please open a discussion (link on the right).  A team member will respond and if needed create an issue.
