blank_issues_enabled: false
contact_links:
  - name: xDrip Discussions
    url: https://github.com/NightscoutFoundation/xDrip/discussions
    about: Your feedback is very valuable.  Thanks for taking the time to provide it.  Please use "Discussions" (link on the right) to go to Discussions.  Then, click on "New discussion" to start a new thread.  
