blank_issues_enabled: false
contact_links:
  - name: xDrip Discussions
    url: https://github.com/NightscoutFoundation/xDrip/discussions
    about:  xDrip is for all of us.  Your feedback is very valuable.  Thanks for taking the time to provide it.
Please use "Discussions" (link on the right) to go to Discussions.  Then, click on "New discussion" to start a new thread.  
To report an issue, please include what version of xDrip you are using, what your phone brand and model is, the steps you took that led to the issue.
To submit a request for a new feature, please explain what you need to accomplish that you cannot with xDrip as is.

A team member will respond.  They may point you to an existing open issue or discussion.  They may explain a workaround to avoid the issue.  They may provide a guide that explains how youc an accomplish what you need with xDrip as is.  
Or, the team member may label the discussion so that the developers know what needs their attention.  
We need to work together to keep improving and maintaining xDrip.  Thanks for your help.
